---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    name: redis-deploy
    app: demo-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: demo-catalog-service
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-catalog-service
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
      restartPolicy: Always  